### PR TITLE
Remove dist directory in .gitignore file

### PR DESCRIPTION
**Pull request by ImMin5**
Signed-off-by: Minho Kim <mino@megazone.com>

### Category
- [ ] New feature
- [ ] Bug fix
- [ ] Improvement
- [ ] Refactor
- [x] etc

### Description
- Remove dist directory in .gitignore file

### Known issue

### CODE REVIEW

**Comment by jihyungSong** [comment]
Please explain why remove dist in .gitignore.

**Comment by ImMin5** [comment]
> Please explain why remove dist in .gitignore.

It is one of process for grpc-gateway.
In case of go, if you using url as import path then you can import .go source file.

As up load .go files in dist directory, we can use at each of cloudforet's micro service.

**Comment by jihyungSong** [comment]
Currently, compiled protobuffer files for each language are generated in the `dist` directory, and this step is executed through Github action.

You can check the "pypi dev test" flow.
After executing a build steps as below, protobuf file will be created in the `dist` directory.

https://github.com/cloudforet-io/api/blob/bda83b83ce965b007c904c6ac6d34d0c818fa615/.github/workflows/CI_pypi_devTest.yml#L60-L65

I have a question.
What stage do you plan to use the protobuffer file for golang to be used in grpc-gateway?

**Comment by jihyungSong** [comment]
If the protobuf file is stored in the dist directory on code, the developer who modified the sources must execute a protobuf build each time and push it.

**Pull request merged**
